import config


# Game Sceneの定数
PILE_COUNT = 8  # 山の個数
STONE_MAX = 20  # 山ごとの石の個数の上限

# 枠組みの座標
HALF_LINE_X = 35
HALF_LINE_TOP_Y = 1
HALF_LINE_BOTTOM_Y = config.WINDOW_HEIGHT - 4

# テキストボックスの座標
TEXT_BOX_TOP_Y = 28
TEXT_BOX_BOTTOM_Y = 31
TEXT_BOX_LEFT_X = 3
TEXT_BOX_RIGHT_X = 32

# 警告の枠の座標
CAUTION_BOX_TOP_Y = 32
CAUTION_BOX_BOTTOM_Y = 34
CAUTION_BOX_LEFT_X = 3
CAUTION_BOX_RIGHT_X = 68

# 盤面の座標
FIELD_TOP_Y = 2
FIELD_BOTTOM_Y = 27
FIELD_LEFT_X = 3
FIELD_RIGHT_X = 32

# 盤面 -> 下の線の座標
PILE_LINE_Y = FIELD_BOTTOM_Y - 3
PILE_LINE_LEFT_X = FIELD_LEFT_X + 2
PILE_LINE_RIGHT_X = FIELD_RIGHT_X - 2

# 盤面 -> 下の番号の座標
PILE_NUMBER_Y = FIELD_BOTTOM_Y - 2
PILE_NUMBER_LEFT_X = FIELD_LEFT_X + 9
PILE_NUMBER_RIGHT_X = PILE_NUMBER_LEFT_X + 2 * PILE_COUNT

# 盤面 -> 目盛りの線の座標
SCALE_LINE_TOP_Y = FIELD_TOP_Y + 2
SCALE_LINE_BOTTOM_Y = SCALE_LINE_TOP_Y + STONE_MAX
SCALE_LINE_X = FIELD_LEFT_X + 5

# 盤面 -> 目盛りの番号の座標
SCALE_NUMBER_TOP_Y = FIELD_TOP_Y + 2
SCALE_NUMBER_BOTTOM_Y = SCALE_NUMBER_TOP_Y + STONE_MAX
SCALE_NUMBER_X = FIELD_LEFT_X + 3

# 盤面 -> 石のmatrixの座標
MATRIX_TOP_Y = 4
MATRIX_BOTTOM_Y = 23
MATRIX_LEFT_X = 12
MATRIX_RIGHT_X = 26

# ゲームログの枠の座標
GAMELOG_BOX_TOP_Y = 2
GAMELOG_BOX_BOTTOM_Y = 31
GAMELOG_BOX_LEFT_X = 38
GAMELOG_BOX_RIGHT_X = 68

# ゲームログのテキストの座標
GAMELOG_TEXT_TOP_Y = GAMELOG_BOX_TOP_Y + 2
GAMELOG_TEXT_BOTTOM_Y = GAMELOG_BOX_BOTTOM_Y - 2
GAMELOG_TEXT_LEFT_X = GAMELOG_BOX_LEFT_X + 2
GAMELOG_TEXT_RIGHT_X = GAMELOG_BOX_RIGHT_X - 2

# カーソル初期値
DEFAULT_PILE_SELECT_CURSOR_X = PILE_NUMBER_LEFT_X
DEFAULT_PILE_SELECT_CURSOR_Y = SCALE_NUMBER_BOTTOM_Y + 1
